- name: Testing ping module
  hosts: all
  become: true
  tasks:
          - name: installing apache2
            apt:
              name: apache2
              state: latest
          - name: installing telnet
            apt:
              name: telnet
              state: latest
          - name: adding index.html
            copy:
               src: myindex.html
               dest: /var/www/html/index.html
          - name: restarting apache2 service
            service:
                name: apache2
                state: restarted
